services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nest-contact-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env.docker
    networks:
      - nest-app

  postgres:
    image: postgres:15-alpine
    container_name: nest-contact-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contact_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nest-app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    depends_on:
      - prometheus

networks:
  nest-app:
    driver: bridge

volumes:
  postgres-data:
    driver: local
